AWSTemplateFormatVersion:    2010-09-09

Description:                 security groups needed

Resources:
  EC2InstanceSecurityGroup:
    Type:                    AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:      security group to allow ssh access
      SecurityGroupIngress:
        - CidrIp:            45.112.186.36/32
          IpProtocol:        tcp
          FromPort:          22
          ToPort:            22

Outputs:
  EC2InstanceSecurityGroup:
    Description:             security group to allow ssh access on ec2 EC2InstanceSecurityGroup
    Value:                   !Ref EC2InstanceSecurityGroup
    Export:
      Name:                  !Sub ${AWS::StackName}::EC2InstanceSecurityGroup
