AWSTemplateFormatVersion:              2010-09-09

Description:                           contains elastic network interface configuration

Parameters:
  AvailableSubnetId1:
    Type:                              String
    Default:                           subnet-085dcd44
  AvailableSubnetId2:
    Type:                              String
    Default:                           subnet-82b192ea
  AvailableSubnetId3:
    Type:                              String
    Default:                           subnet-f8a87283

Resources:
  SimpleElasticNetworkInterface1:
    Type:                              AWS::EC2::NetworkInterface
    Properties:
      SecondaryPrivateIpAddressCount:  1
      SubnetId:                        !Ref AvailableSubnetId1
      GroupSet:
        - !ImportValue master-sg::EC2SSHSecurityGroupId
  SimpleElasticNetworkInterface2:
    Type:                              AWS::EC2::NetworkInterface
    Properties:
      SecondaryPrivateIpAddressCount:  1
      SubnetId:                        !Ref AvailableSubnetId2
      GroupSet:
        - !ImportValue master-sg::EC2SSHSecurityGroupId
  SimpleElasticNetworkInterface3:
    Type:                              AWS::EC2::NetworkInterface
    Properties:
      SecondaryPrivateIpAddressCount:  1
      SubnetId:                        !Ref AvailableSubnetId3
      GroupSet:
        - !ImportValue master-sg::EC2SSHSecurityGroupId

Outputs:
  SimpleElasticNetworkInterface1:
    Description:                       a simple elastic network interface
    Value:                             !Ref SimpleElasticNetworkInterface1
    Export:
      Name:                            !Sub ${AWS::StackName}::SimpleElasticNetworkInterface1
  SimpleElasticNetworkInterface2:
    Description:                       a simple elastic network interface
    Value:                             !Ref SimpleElasticNetworkInterface2
    Export:
      Name:                            !Sub ${AWS::StackName}::SimpleElasticNetworkInterface2
  SimpleElasticNetworkInterface3:
    Description:                       a simple elastic network interface
    Value:                             !Ref SimpleElasticNetworkInterface3
    Export:
      Name:                            !Sub ${AWS::StackName}::SimpleElasticNetworkInterface3
