AWSTemplateFormatVersion:                      2010-09-09

Description:                                   simple application load balancers

Resources:
  ExternalApplicationLoadBalancerTargetGroup:
    Type:                                      AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled:                      true
      HealthCheckIntervalSeconds:              5
      HealthCheckPath:                         /
      HealthCheckPort:                         80
      HealthCheckProtocol:                     HTTP
      HealthCheckTimeoutSeconds:               3
      HealthyThresholdCount:                   2
      UnhealthyThresholdCount :                2
      Port:                                    80
      Protocol:                                HTTP
      VpcId:                                   vpc-38424750
  ExternalApplicationLoadBalancerListener:
    Type:                                      AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:                         !Ref ExternalApplicationLoadBalancer
      Protocol:                                HTTP
      Port:                                    80
      DefaultActions:
        - Type:                                forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:                !Ref ExternalApplicationLoadBalancerTargetGroup
  ExternalApplicationLoadBalancer:
    Type:                                      AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType:                           ipv4
      Scheme:                                  internet-facing
      Type:                                    application
      Subnets:
        - subnet-085dcd44
        - subnet-82b192ea
        - subnet-f8a87283
      SecurityGroups:
        - !ImportValue master-sg::InternetFacingLoadBalancerSecurityGroupId

Outputs:
  ExternalApplicationLoadBalancer:
    Description:                               simple external load balancer
    Value:                                     !Ref ExternalApplicationLoadBalancer
    Export:
      Name:                                    !Sub ${AWS::StackName}::ExternalApplicationLoadBalancer
  ExternalApplicationLoadBalancerTargetGroup:
    Description:                               target group to forward requests to
    Value:                                     !Ref ExternalApplicationLoadBalancerTargetGroup
    Export:
      Name:                                    !Sub ${AWS::StackName}::ExternalApplicationLoadBalancerTargetGroup
