AWSTemplateFormatVersion:                           2010-09-09

Resources:
  InternetFacingLoadBalancer:
    Type:                                           AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType:                                ipv4
      Scheme:                                       internet-facing
      Subnets:
        - subnet-085dcd44
        - subnet-82b192ea
        - subnet-f8a87283
      SecurityGroups:
        - !ImportValue master-sg::InternetFacingALBSecurityGroupId
      Type:                                         application
  StudentAPICallTargetGroup:
    Type:                                           AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:                                        vpc-38424750
      HealthCheckEnabled:                           true
      HealthCheckIntervalSeconds:                   10
      HealthCheckPath:                              /api/v1/health
      HealthCheckPort:                              8080
      HealthCheckProtocol:                          HTTP
      HealthCheckTimeoutSeconds:                    5
      HealthyThresholdCount:                        2
      Matcher:
        HttpCode:                                   200
      Port:                                         8080
      Protocol:                                     HTTP
      TargetType:                                   instance
      Targets:
        - Id:                                       !ImportValue master-ec2::SimpleEC2Instance1
          Port:                                     8080
  PersonAPICallTargetGroup:
    Type:                                           AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:                                        vpc-38424750
      HealthCheckEnabled:                           true
      HealthCheckIntervalSeconds:                   10
      HealthCheckPath:                              /api/v1/health
      HealthCheckPort:                              8080
      HealthCheckProtocol:                          HTTP
      HealthCheckTimeoutSeconds:                    5
      HealthyThresholdCount:                        2
      Matcher:
        HttpCode:                                   200
      Port:                                         8080
      Protocol:                                     HTTP
      TargetType:                                   instance
      Targets:
        - Id:                                       !ImportValue master-ec2::SimpleEC2Instance2
          Port:                                     8080
  APICallListener:
    Type:                                           AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port:                                         80
      Protocol:                                     HTTP
      LoadBalancerArn:                              !Ref InternetFacingLoadBalancer
      DefaultActions:
        - Type:                                     forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:                     !Ref    StudentAPICallTargetGroup
                Weight:                             1
              - TargetGroupArn:                     !Ref    PersonAPICallTargetGroup
                Weight:                             1
  StudentAPICallListenerRule:
    Type:                                           AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority:                                     1
      ListenerArn:                                  !Ref APICallListener
      Actions:
        - Type:                                     forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:                     !Ref    StudentAPICallTargetGroup
      Conditions:
        - Field:                                    path-pattern
          PathPatternConfig:
            Values:
              - /api/*/students/*
  PersonAPICallListenerRule:
    Type:                                           AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority:                                     2
      ListenerArn:                                  !Ref APICallListener
      Actions:
        - Type:                                     forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:                     !Ref    PersonAPICallTargetGroup
      Conditions:
        - Field:                                    path-pattern
          PathPatternConfig:
            Values:
              - /api/*/people/*

Outputs:
  InternetFacingLoadBalancerDNSName:
    Value:                                          !GetAtt InternetFacingLoadBalancer.DNSName
    Export:
      Name:                                         !Sub ${AWS::StackName}::InternetFacingLoadBalancerDNSName
  InternetFacingLoadBalancerCanonicalHostedZoneID:
    Value:                                          !GetAtt InternetFacingLoadBalancer.CanonicalHostedZoneID
    Export:
      Name:                                         !Sub ${AWS::StackName}::InternetFacingLoadBalancerCanonicalHostedZoneID
