AWSTemplateFormatVersion: 2010-09-09

Description:              This contains ec2 instance deployment

Parameters:
  AmazonLinuxImageId:
    Type:                 String
    Default:              ami-051dfee3fa484ecce
  MumbaiAZ1:
    Type:                 String
    Default:              ap-south-1a
  FreeTierInstanceType:
    Type:                 String
    Default:              t2.small

Resources:
  SimpleEC2Instance:
    Type:                 AWS::EC2::Instance
    Properties:
      AvailabilityZone:   !Ref MumbaiAZ1
      ImageId:            !Ref AmazonLinuxImageId
      InstanceType:       !Ref FreeTierInstanceType
      KeyName:            aws-kp
      SecurityGroupIds:
        - !ImportValue master-sg::EC2SecurityGroupId
      UserData:
        Fn::Base64:       !Sub |
          #!/bin/bash
          sudo su
          yum update -y
          yum install git -y
          cd /home/ec2-user/
          git clone https://github.com/kalikirisrikarreddy/student-api
          chmod 0755 /home/ec2-user/student-api
          yum install java-1.8.0-openjdk -y
          yum install maven -y
          mvn -f /home/ec2-user/student-api/pom.xml clean install
          touch /home/ec2-user/ws-boot.sh
          touch /etc/systemd/system/student_api.service
          echo "java -Xms128M -Xmx256M -XX:MaxMetaspaceSize=128M -Dspring.profiles.active=dev -jar /home/ec2-user/student-api/target/student-api-0.0.1-SNAPSHOT.jar" >> /home/ec2-user/ws-boot.sh
          chmod 744 /home/ec2-user/ws-boot.sh
          echo "[Unit]" >> /etc/systemd/system/student_api.service
          echo "Description=Student API Service" >> /etc/systemd/system/student_api.service
          echo "[Service]" >> /etc/systemd/system/student_api.service
          echo "User=ec2-user" >> /etc/systemd/system/student_api.service
          echo "#change this directory into your workspace" >> /etc/systemd/system/student_api.service
          echo "WorkingDirectory=/home/ec2-user/student-api" >> /etc/systemd/system/student_api.service
          echo "#path to the executable bash script which executes the jar file" >> /etc/systemd/system/student_api.service
          echo "ExecStart=/bin/bash /home/ec2-user/ws-boot.sh" >> /etc/systemd/system/student_api.service
          echo "SuccessExitStatus=143" >> /etc/systemd/system/student_api.service
          echo "TimeoutStopSec=600" >> /etc/systemd/system/student_api.service
          echo "Restart=on-failure" >> /etc/systemd/system/student_api.service
          echo "RestartSec=600" >> /etc/systemd/system/student_api.service
          echo "[Install]" >> /etc/systemd/system/student_api.service
          echo "WantedBy=multi-user.target" >> /etc/systemd/system/student_api.service
          chmod 744 /etc/systemd/system/student_api.service
          systemctl daemon-reload
          systemctl enable student_api.service
          systemctl start student_api
          systemctl status student_api -l

Outputs:
  SimpleEC2Instance:
    Description:          A simple ec2 instance
    Value:                !Ref SimpleEC2Instance
    Export:
      Name:               !Sub ${AWS::StackName}::SimpleEC2Instance
