AWSTemplateFormatVersion:                   2010-09-09

Description:                                intantiate security groups

Resources:
  InternetFacingLoadBalancerSecurityGroup:
    Type:                                   AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:                     for internet facing load balancer
      SecurityGroupIngress:
        - CidrIp:                           0.0.0.0/0
          IpProtocol:                       tcp
          FromPort:                         80
          ToPort:                           80
  EC2SecurityGroup:
    Type:                                   AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:                     for auto scaling group
      SecurityGroupIngress:
        - SourceSecurityGroupId:            !GetAtt InternetFacingLoadBalancerSecurityGroup.GroupId
          IpProtocol:                       tcp
          FromPort:                         80
          ToPort:                           80

Outputs:
  InternetFacingLoadBalancerSecurityGroup:
    Description:                            internet facing load balancer security group
    Value:                                  !GetAtt InternetFacingLoadBalancerSecurityGroup.GroupId
    Export:
      Name:                                 !Sub ${AWS::StackName}::InternetFacingLoadBalancerSecurityGroupId
  EC2SecurityGroup:
    Description:                            auto scaling group security group
    Value:                                  !GetAtt EC2SecurityGroup.GroupId
    Export:
      Name:                                 !Sub ${AWS::StackName}::EC2SecurityGroupId
