AWSTemplateFormatVersion:    2010-09-09

Resources:
  SimpleECRRepo:
    Type:                    AWS::ECR::Repository
    Properties:
      RepositoryName:        simple-ecr-repo
      RepositoryPolicyText:
        Statement:
          - Sid:             allow all ecr actions to users in my account
            Effect:          Allow
            Principal:
               Service:
                 - ecs.amazonaws.com
                 - ecs-tasks.amazonaws.com
            Action:          ecr:*

Outputs:
  SimpleECRRepoId:
    Value:                   !Ref SimpleECRRepo
    Export:
      Name:                  !Sub ${AWS::StackName}::SimpleECRRepoId
  SimpleECRRepoArn:
    Value:                   !GetAtt SimpleECRRepo.Arn
    Export:
      Name:                  !Sub ${AWS::StackName}::SimpleECRRepoArn
