AWSTemplateFormatVersion:       2010-09-09

Resources:
  SimpleECSCluster:
    Type:                       AWS::ECS::Cluster
    Properties:
      ClusterName:              simple-ecs-cluster
  SimpleECSTask:
    Type:                       AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn:         !ImportValue master-iam::SimpleExecutionRoleArn
      TaskRoleArn:              !ImportValue master-iam::SimpleECSTaskRoleArn
      ContainerDefinitions:
        - Environment:
            - Name:             ENVIRONMENT
              Value:            dev
          Image:                058363540711.dkr.ecr.ap-south-1.amazonaws.com/simple-ecr-repo:latest
          PortMappings:
            - ContainerPort:    8080
          Essential:            true
          Name:                 student-api
      Cpu:                      256
      Memory:                   512
      NetworkMode:              awsvpc
      RequiresCompatibilities:
        - FARGATE
  SimpleECSService:
    Type:                       AWS::ECS::Service
    Properties:
      Cluster:                  !Ref SimpleECSCluster
      DesiredCount:             1
      LaunchType:               FARGATE
      ServiceName:              simple-ecs-service
      TaskDefinition:           !Ref SimpleECSTask
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue master-sg::SimpleSecurityGroup2Id
          Subnets:
            - !ImportValue  master-vpc::PrivateSubNet1ID
            - !ImportValue  master-vpc::PrivateSubNet2ID
            - !ImportValue  master-vpc::PrivateSubNet3ID

Outputs:
  SimpleECSClusterId:
    Value:                      !Ref SimpleECSCluster
    Export:
      Name:                     !Sub ${AWS::StackName}::SimpleECSClusterId
  SimpleECSClusterArn:
    Value:                      !GetAtt SimpleECSCluster.Arn
    Export:
      Name:                     !Sub ${AWS::StackName}::SimpleECSClusterArn
  SimpleECSTaskArn:
    Value:                      !Ref SimpleECSTask
    Export:
      Name:                     !Sub ${AWS::StackName}::SimpleECSTaskArn
  SimpleECSServiceArn:
    Value:                      !Ref SimpleECSService
    Export:
      Name:                     !Sub ${AWS::StackName}::SimpleECSServiceArn
  SimpleECSServiceName:
    Value:                      !GetAtt SimpleECSService.Name
    Export:
      Name:                     !Sub ${AWS::StackName}::SimpleECSServiceName
