AWSTemplateFormatVersion:   2010-09-09

Description:                '''
                            contains declaration of ec2 instance deployment
                            into a placement group
                            '''

Parameters:
  AmazonLinuxImageId:
    Type:                   String
    Default:                ami-051dfee3fa484ecce
  MumbaiAZ1:
    Type:                   String
    Default:                ap-south-1a
  FreeTierInstanceType:
    Type:                   String
    Default:                t2.micro

Resources:
  ClusterPlacementGroup:
    Type:                   AWS::EC2::PlacementGroup
    Properties:
       Strategy:            cluster
  PartitionPlacementGroup:
    Type:                   AWS::EC2::PlacementGroup
    Properties:
       Strategy:            partition
  SpreadPlacementGroup:
    Type:                   AWS::EC2::PlacementGroup
    Properties:
       Strategy:            spread
  SimpleEC2Instance1:
    Type:                   AWS::EC2::Instance
    Properties:
      AvailabilityZone:     !Ref MumbaiAZ1
      ImageId:              !Ref AmazonLinuxImageId
      InstanceType:         !Ref FreeTierInstanceType
      KeyName:              aws-kp
      SecurityGroups:
        - !ImportValue master-sg::SimpleSecurityGroup
      #t2 micro instance type is not compatible with cluster placement group
      #PlacementGroupName:   !Ref ClusterPlacementGroup
      PlacementGroupName:   !Ref PartitionPlacementGroup
  SimpleEC2Instance2:
    Type:                   AWS::EC2::Instance
    Properties:
      AvailabilityZone:     !Ref MumbaiAZ1
      ImageId:              !Ref AmazonLinuxImageId
      InstanceType:         !Ref FreeTierInstanceType
      KeyName:              aws-kp
      SecurityGroups:
        - !ImportValue master-sg::SimpleSecurityGroup
      PlacementGroupName:   !Ref PartitionPlacementGroup
  SimpleEC2Instance3:
    Type:                   AWS::EC2::Instance
    Properties:
      AvailabilityZone:     !Ref MumbaiAZ1
      ImageId:              !Ref AmazonLinuxImageId
      InstanceType:         !Ref FreeTierInstanceType
      KeyName:              aws-kp
      SecurityGroups:
        - !ImportValue master-sg::SimpleSecurityGroup
      PlacementGroupName:   !Ref SpreadPlacementGroup

Outputs:
  ClusterPlacementGroup:
    Description:            cluster placement group
    Value:                  !Ref ClusterPlacementGroup
    Export:
      Name:                 !Sub ${AWS::StackName}::ClusterPlacementGroup
  PartitionPlacementGroup:
    Description:            partition placement group
    Value:                  !Ref PartitionPlacementGroup
    Export:
      Name:                 !Sub ${AWS::StackName}::PartitionPlacementGroup
  SpreadPlacementGroup:
    Description:            spread placement group
    Value:                  !Ref SpreadPlacementGroup
    Export:
      Name:                 !Sub ${AWS::StackName}::SpreadPlacementGroup
  SimpleEC2Instance1:
    Description:            simple ec2 instance
    Value:                  !Ref SimpleEC2Instance1
    Export:
      Name:                 !Sub ${AWS::StackName}::SimpleEC2Instance1
  SimpleEC2Instance2:
    Description:            simple ec2 instance
    Value:                  !Ref SimpleEC2Instance2
    Export:
      Name:                 !Sub ${AWS::StackName}::SimpleEC2Instance2
  SimpleEC2Instance3:
    Description:            simple ec2 instance
    Value:                  !Ref SimpleEC2Instance3
    Export:
      Name:                 !Sub ${AWS::StackName}::SimpleEC2Instance3
