AWSTemplateFormatVersion:    2010-09-09

Description:                 cloud watch alarms for various ec2 metrics provided by aws

Resources:
  HighNetworkOutBytesAlarm:
    Type:                    AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled:        FALSE
      MetricName:            NetworkOut
      Namespace:             AWS/EC2
      AlarmDescription:      this alarm is meant to signal/notify high network traffic
      ComparisonOperator:    GreaterThanThreshold
      DatapointsToAlarm:     1
      Dimensions:
        - Name:              InstanceId
          Value:             !ImportValue master-ec2::SimpleEC2Instance
      EvaluationPeriods:     1
      Period:                300
      Statistic:             Maximum
      Threshold:             40000
      Unit:                  Bytes
      AlarmActions:
        - arn:aws:automate:ap-south-1:ec2:stop

Outputs:
  HighNetworkOutBytesAlarm:
    Description:             this alarm is meant to signal/notify high network traffic
    Value:                   !Ref HighNetworkOutBytesAlarm
    Export:
      Name:                  !Sub ${AWS::StackName}::HighNetworkOutBytesAlarm
